modifying request of comments
Activiti/incubator pull request #1
Opened 2018-03-29 10:28 UTC by MiguelRuizDev

2018-03-29 10:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/incubator?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/incubator?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/incubator?pullRequest=1) it.</sub>

2018-04-03 14:30 UTC, erdemedeiros requested changes
Some comments plus write some tests.

2018-04-03 14:30 UTC, erdemedeiros commented on task-service/pom.xml
> +            <version>1.1.0.RELEASE</version>
Based on our discussion you can remove this dependency.

2018-04-03 14:30 UTC, erdemedeiros commented on task-service/src/main/java/org/activiti/incubator/taskservice/JpaJacksonConverter.java
> +        import java.io.IOException;
Please, remove commented code. Add it later when necessary.

2018-04-03 14:30 UTC, erdemedeiros commented on task-service/src/main/java/org/activiti/incubator/taskservice/Task.java
> +    private Long id;
Will need to move to UUIDs (String) in the future.

2018-04-03 14:30 UTC, erdemedeiros commented on task-service/src/main/java/org/activiti/incubator/taskservice/Task.java
> +    private Long  parent; //stores parent's id; if there is no parent, id = -1
Remove comments not directly related to the code.

2018-04-03 14:30 UTC, erdemedeiros commented on task-service/src/main/java/org/activiti/incubator/taskservice/Task.java
> +    //constructor
Not necessary (constructor and comment) .

2018-04-03 14:30 UTC, erdemedeiros commented on task-service/src/main/java/org/activiti/incubator/taskservice/Task.java
> +    //getters and setters
Unnecessary comment.

2018-04-03 14:30 UTC, erdemedeiros commented on task-service/src/main/java/org/activiti/incubator/taskservice/Task.java
> +    public void setTitle(String title) { this.title = title; }
You can try to remove the setters, I'm not sure if they are necessary.

2018-04-03 14:30 UTC, erdemedeiros commented on task-service/src/main/java/org/activiti/incubator/taskservice/TaskController.java
> +    TaskRepository db; //injection
Unnecessary comment + find a better name for the variable.

2018-04-03 14:30 UTC, erdemedeiros commented on task-service/src/main/java/org/activiti/incubator/taskservice/TaskController.java
> +    @RequestMapping(path = "/tasks/{id}/suspend", method = RequestMethod.POST) //whenever you don't know which one to use
Check the best verb for this use case (patch?) + you can use `@PostRequest`/`@PatchResquest`, instead of `@RequestMapping` + remove comment.

2018-04-03 14:30 UTC, erdemedeiros commented on task-service/src/main/java/org/activiti/incubator/taskservice/TaskController.java
> +        Task task = db.findById(id).get(); //java8 optionals
Unnecessary comment.

2018-04-03 14:30 UTC, erdemedeiros commented on task-service/src/main/java/org/activiti/incubator/taskservice/TaskController.java
> +        }
Remove or implement something inside the empty else block.

2018-05-28 00:39 UTC, Salaboy commented
@erdemedeiros @MiguelRuizDev guys.. I need to merge this project to develop so I can share the link with people interested in contributing.. is that ok with all of you? @MiguelRuizDev if you have changes please push them. Also create another directory called task-runtime-ui with the Angular code.. so we can try to run in our environments.

2018-05-29 09:04 UTC, erdemedeiros approved these changes

2018-05-29 09:05 UTC, erdemedeiros commented
@Salaboy I'm ok with merging it.

2018-05-29 18:45 UTC, merged